### ISSUE TITLE
Errors in newer versions of BurpSuite

### ISSUE THREAD

**Issue by Nzoth9** [mdsecresearch/BurpSuiteSharpener#101]
```
A failure in get_rootTabbedPaneUsingMontoya() has occurred. Hopefully this will be recovered now.
A failure in get_rootTabbedPaneUsingMontoya() has occurred. Hopefully this will be recovered now.
A failure in get_rootTabbedPaneUsingMontoya() has occurred. Hopefully this will be recovered now.
A failure in get_rootTabbedPaneUsingMontoya() has occurred. Hopefully this will be recovered now.
A failure in get_rootTabbedPaneUsingMontoya() has occurred. Hopefully this will be recovered now.
A failure in get_rootTabbedPaneUsingMontoya() has occurred. Hopefully this will be recovered now.
A failure in get_rootTabbedPaneUsingMontoya() has occurred. Hopefully this will be recovered now.
A failure in get_rootTabbedPaneUsingMontoya() has occurred. Hopefully this will be recovered now.
A failure in get_rootTabbedPaneUsingMontoya() has occurred. Hopefully this will be recovered now.
A failure in get_rootTabbedPaneUsingMontoya() has occurred. Hopefully this will be recovered now.
Sharpener extension UI elements could not be added. Please try again.
java.lang.ClassNotFoundException: ninja.burpsuite.libs.objects.PreferenceObject
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at ninja.burpsuite.extension.sharpener.ExtensionGeneralSettings.definePreferenceObjectCollection(ExtensionGeneralSettings.java:51)
	at ninja.burpsuite.libs.objects.StandardSettings.<init>(StandardSettings.java:20)
	at ninja.burpsuite.extension.sharpener.ExtensionGeneralSettings.<init>(ExtensionGeneralSettings.java:38)
	at ninja.burpsuite.extension.sharpener.ExtensionMainClass.initializeSettings(ExtensionMainClass.java:124)
	at ninja.burpsuite.extension.sharpener.ExtensionMainClass.furtherLoadingChecks(ExtensionMainClass.java:133)
	at ninja.burpsuite.extension.sharpener.ExtensionMainClass.initialize(ExtensionMainClass.java:56)
	at burp.Zzjj.ZS(Unknown Source)
	at burp.Zcp_.Zc(Unknown Source)
	at burp.Zcpk.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

**Comment by irsdl** [comment]
This repo is not maintained. Could you please report it in https://github.com/irsdl/BurpSuiteSharpenerEx with more details including burp suite version, OS, and sharpener version? Also please explain when it happens so I can try to recreate it.

**Comment by Nzoth9** [comment]
@irsdl This appears to be fixed in the latest version. Thanks.
